import AppKit
import Foundation

/// Vigila NSPasteboard.general por cambios (changeCount) y guarda lo copiado.
/// macOS no ofrece notificaciones de portapapeles, así que se hace polling ligero.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount

    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private init() {}

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Llamar después de escribir en el portapapeles desde la propia app para no re-capturarlo.
    func markOwnWrite() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        guard !Prefs.clipboardPausedValue else { return }

        let types = pb.types ?? []
        if types.contains(Self.concealed) || types.contains(Self.transient) || types.contains(Self.autoGenerated) {
            return
        }

        let source = SourceApp.frontmost
        if let bid = source.bundleID, Prefs.ignoredBundleIDs.contains(bid) { return }

        let store = ClipStore.shared

        // 1. Archivos
        if types.contains(.fileURL),
           let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            for url in urls { store.addFile(url, source: source) }
            return
        }

        // 2. Imágenes
        let hasImageType = types.contains(.png) || types.contains(.tiff)
        if hasImageType, let image = NSImage(pasteboard: pb), let png = ImageStore.pngData(from: image) {
            if let item = store.addImage(pngData: png, kind: .image, source: source) {
                OCRService.runIfEnabled(for: item)
            }
            return
        }

        // 3. Texto
        guard let raw = pb.string(forType: .string) else { return }
        let text = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return }
        if Prefs.skipSensitiveValue, SensitiveContentDetector.isSensitive(text) { return }

        store.addText(raw, kind: ContentClassifier.classify(text), source: source)
    }
}

enum ContentClassifier {
    static func classify(_ text: String) -> ClipKind {
        let singleLine = !text.contains("\n")

        if singleLine, let url = URL(string: text), let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "ssh", "mailto"].contains(scheme), url.host != nil || scheme == "mailto" {
            return .link
        }

        if singleLine, isColor(text) { return .color }

        if looksLikeCode(text) { return .code }
        return .text
    }

    static func isColor(_ s: String) -> Bool {
        let hex = "^#([0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$"
        let fn = "^(rgb|rgba|hsl|hsla)\\([^)]*\\)$"
        return s.range(of: hex, options: .regularExpression) != nil
            || s.range(of: fn, options: [.regularExpression, .caseInsensitive]) != nil
    }

    static func looksLikeCode(_ s: String) -> Bool {
        let lines = s.split(separator: "\n", omittingEmptySubsequences: false)
        guard lines.count >= 2 || s.count > 40 else { return false }
        var score = 0
        let markers = ["{", "}", ";", "=>", "->", "==", "!=", "&&", "||", "</", "/>", "#include", "import ", "func ", "def ", "class ", "return ", "const ", "let ", "var ", "public ", "private ", "$(", "&&", "| ", "sudo ", "curl ", "SELECT ", "FROM "]
        for m in markers where s.contains(m) { score += 1 }
        let indented = lines.filter { $0.hasPrefix("    ") || $0.hasPrefix("\t") }.count
        if indented >= 2 { score += 2 }
        if s.range(of: "^\\s*(\\$|#|>)\\s", options: .regularExpression) != nil { score += 1 }
        return score >= 3
    }
}
